"""Add done_by_user_id and done_on_behalf_of_user_id to Notification

Revision ID: 2d87ded02b5f
Revises: 1088c62f380e
Create Date: 2024-11-11 14:34:32.224346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d87ded02b5f'
down_revision = '1088c62f380e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('done_on_behalf_of_user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('done_on_behalf_of_user_id')
        batch_op.drop_column('done_by_user_id')

    # ### end Alembic commands ###
