"""Add zone_score and facility_score to TaskSubmission

Revision ID: 580a5bc2d162
Revises: d8e95b797fc3
Create Date: 2024-10-19 06:49:25.482778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580a5bc2d162'
down_revision = 'd8e95b797fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('facility_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_submission', schema=None) as batch_op:
        batch_op.drop_column('facility_score')
        batch_op.drop_column('zone_score')

    # ### end Alembic commands ###
