"""Add many-to-many relationship between User and Office 1

Revision ID: 631173b8bd8f
Revises: b6fd9f07707b
Create Date: 2024-10-26 22:10:51.545793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631173b8bd8f'
down_revision = 'b6fd9f07707b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_office',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'office_id')
    )
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.drop_constraint('office_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('office_user_id_fkey', 'user', ['user_id'], ['id'])

    op.drop_table('user_office')
    # ### end Alembic commands ###
