"""Add first_name, middle_name, last_name to User model

Revision ID: 699cd70be96e
Revises: 751b68a3c06c
Create Date: 2024-10-23 14:15:56.572868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699cd70be96e'
down_revision = '751b68a3c06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
