"""Add sector field to Office

Revision ID: 751b68a3c06c
Revises: e7b247c569df
Create Date: 2024-10-23 11:31:05.976844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751b68a3c06c'
down_revision = 'e7b247c569df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.alter_column('sector',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.alter_column('sector',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
