"""empty message

Revision ID: a63a28f46464
Revises: dedd899c0957
Create Date: 2024-11-08 08:56:48.003683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a63a28f46464'
down_revision = 'dedd899c0957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('office_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('monthly_score_summary', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('office_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('zone_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('total_zone_score',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_facility_score',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'office', ['office_id'], ['id'])

    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('sector',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('zone',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('office_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'office', ['office_id'], ['id'])

    with op.batch_alter_table('task_submission', schema=None) as batch_op:
        batch_op.alter_column('task_type',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('room_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('room_score',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('area_scores',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('zone_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('zone_score',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('facility_score',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'room', ['room_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('middle_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('password_change_required',
               existing_type=mysql.CHAR(collation='utf8_unicode_ci', length=1),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('user_office', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'office', ['office_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_office', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_change_required',
               existing_type=sa.Boolean(),
               type_=mysql.CHAR(collation='utf8_unicode_ci', length=1),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
        batch_op.alter_column('middle_name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('task_submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('facility_score',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
        batch_op.alter_column('zone_score',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
        batch_op.alter_column('zone_name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('area_scores',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('room_score',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
        batch_op.alter_column('room_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('task_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('office_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('zone',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('sector',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('monthly_score_summary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('total_facility_score',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
        batch_op.alter_column('total_zone_score',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
        batch_op.alter_column('zone_name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('office_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('month',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('office_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
