"""Added room_score, area_scores, and zone_name to TaskSubmission

Revision ID: d8e95b797fc3
Revises: e47bd074bba2
Create Date: 2024-10-18 11:57:35.312246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e95b797fc3'
down_revision = 'e47bd074bba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('area_scores', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('zone_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_submission', schema=None) as batch_op:
        batch_op.drop_column('zone_name')
        batch_op.drop_column('area_scores')
        batch_op.drop_column('room_score')

    # ### end Alembic commands ###
