"""Add zone column to Room model

Revision ID: e47bd074bba2
Revises: a6ac54d5fa1b
Create Date: 2024-10-13 23:26:24.400563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47bd074bba2'
down_revision = 'a6ac54d5fa1b'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('room', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('zone', sa.String(length=120), nullable=False))

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('room', schema=None) as batch_op:
#         batch_op.drop_column('zone')

    # ### end Alembic commands ###


def upgrade():
    # Add the 'zone' column with a default value for existing rows
    with op.batch_alter_table('room') as batch_op:
        batch_op.add_column(sa.Column('zone', sa.String(length=120), nullable=False, server_default='Unassigned Zone'))

def downgrade():
    # Remove the 'zone' column if we roll back the migration
    with op.batch_alter_table('room') as batch_op:
        batch_op.drop_column('zone')
   
